spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/education_db
    username: postgres
    password: password

  flyway:
    enabled: true
    locations: classpath:db/migration
    clean-disabled: false

jwt:
  secret: dev-secret-only-use-locally
  expiration: 86400000
