spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/virtual_portfolio
    username: postgres
    password: password

  jpa:
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    clean-disabled: false

logging:
  level:
    root: DEBUG
    com.portfolio: DEBUG

jwt:
  secret: dev-secret-only-use-locally
  expiration: 86400000
